version: '3.7'

services:
  ### POSTGRES ###############################################
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=visit_turkey
      - POSTGRES_PASSWORD=visit_turkey
      - POSTGRES_DB=visit_turkey_db
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/data/postgres
    container_name: visit_turkey_postgres
volumes:
  data:
    driver: local
networks:
  local:
    driver: bridge
